"""The MacBook browser worker (§26-§30). An OUTBOUND-only client: it polls the deployed
Render API, claims one task at a time, drives the EXISTING V3 runner against real Chromium
locally, and reports the outcome back. It never listens on a port and never imports the DB —
all state lives behind the API (§13, §14).

LLM calls go back to the API (§28) via RemoteLLMProvider, so no provider keys live here.

Run it with `python -m worker.worker` (PYTHONPATH must include backend/; the Docker image
and scripts/run-browser-worker.sh set that up)."""
from __future__ import annotations

import os
import signal
import socket
import sys
import tempfile
import threading
import time

import httpx

from app.applications import runner
from app.applications.playwright_page import playwright_session
from app.applications.questions import FillContext
from app.models import ApplicationAnswer, ApplicationTask, TaskEvent
from app.providers.llm import LLMError, LLMProvider


# --------------------------------------------------------------------- config #
def _env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


API_BASE = _env("API_BASE_URL").rstrip("/")
TOKEN = _env("WORKER_AUTH_TOKEN")
WORKER_ID = _env("WORKER_ID") or f"mac-{socket.gethostname()}"
POLL_SECONDS = float(_env("WORKER_POLL_SECONDS", "5"))
IDLE_MAX_SECONDS = float(_env("WORKER_IDLE_MAX_SECONDS", "30"))
# Ping the task's heartbeat while a run is in progress — must stay under the server's
# WORKER_HEARTBEAT_TIMEOUT (45s) so a multi-minute application isn't falsely recovered (§18).
HEARTBEAT_SECONDS = float(_env("WORKER_HEARTBEAT_SECONDS", "15"))
HEADLESS = _env("WORKER_HEADLESS", "true").lower() != "false"

_stop = False


def _handle_stop(signum, _frame):
    global _stop
    _stop = True
    print(f"[worker] signal {signum} — finishing current task then exiting", flush=True)


# -------------------------------------------------------------- remote LLM #
class RemoteLLMProvider(LLMProvider):
    """Semantic answers are generated by the API, not here (§28) — keeps keys centralized.
    Only answer_question is used by the runner; the other ops never run on the worker."""
    name = "remote"

    def __init__(self, client: httpx.Client):
        self._client = client

    def _complete(self, system: str, user: str) -> str:  # pragma: no cover - unused here
        raise LLMError("RemoteLLMProvider only supports answer_question on the worker")

    def answer_question(self, question: str, jd: str, evidence: str) -> ApplicationAnswer:
        r = self._client.post("/worker/llm/answer",
                              json={"question": question, "jd": jd, "evidence": evidence})
        if r.status_code != 200:
            raise LLMError(f"remote llm {r.status_code}: {r.text[:200]}")
        return ApplicationAnswer.model_validate(r.json())


# ------------------------------------------------------------------ one task #
def _download_resume(client: httpx.Client, url: str) -> str:
    """Fetch the tailored résumé to a temp file the browser can upload (trap #1)."""
    r = client.get(url)
    r.raise_for_status()
    fd, path = tempfile.mkstemp(prefix="resume_", suffix=".pdf")
    with os.fdopen(fd, "wb") as fh:
        fh.write(r.content)
    return path


def _heartbeat_thread(client: httpx.Client, task_id: int) -> tuple[threading.Thread, threading.Event]:
    """Keep the claim fresh while the (blocking, sync) run is in progress, so it isn't
    recovered as stale mid-application (§18). Stops on the returned Event."""
    stop = threading.Event()

    def loop():
        while not stop.wait(HEARTBEAT_SECONDS):
            try:
                # A short timeout of its own: the shared client's 60s default would let one
                # slow/cold-starting API request eat most of the 45s server-side staleness
                # window all by itself. Failing fast means the next tick, 15s later, gets a
                # real second chance instead of waiting out a single stuck call.
                client.post(f"/worker/tasks/{task_id}/heartbeat",
                            json={"worker_id": WORKER_ID}, timeout=8.0)
            except Exception:  # noqa: BLE001 — a missed ping is not fatal
                pass

    t = threading.Thread(target=loop, daemon=True)
    t.start()
    return t, stop


def _report_crash(client: httpx.Client, task: ApplicationTask, e: Exception) -> None:
    print(f"[worker] task {task.id} crashed: {type(e).__name__}: {e}", flush=True)
    try:
        client.post(f"/worker/tasks/{task.id}/fail", json={
            "worker_id": WORKER_ID, "error_code": "WORKER_ERROR",
            "error_message": f"{type(e).__name__}: {e}",
            # Whatever run_task got through before crashing — a crash shouldn't also
            # throw away the fields it had already filled.
            "questions": [q.model_dump() for q in task.questions],
            "logs": [ev.model_dump() for ev in task.logs],
            "current_page": task.current_page})
    except Exception:  # noqa: BLE001 — API unreachable; stale recovery will catch it
        pass


def _process(client: httpx.Client, claim: dict) -> None:
    task = ApplicationTask.model_validate(claim["task"])
    ctx_data = claim["context"]
    submit = bool(claim["submit"])
    print(f"[worker] claimed task {task.id} (submit={submit})", flush=True)

    resume_path = ""
    hb_thread, hb_stop = _heartbeat_thread(client, task.id)
    try:
        if ctx_data.get("resume_url"):
            resume_path = _download_resume(client, ctx_data["resume_url"])
        ctx = FillContext(
            candidate_values=ctx_data["candidate_values"],
            evidence=ctx_data["evidence"], jd_text=ctx_data["jd_text"],
            supported_skills=set(ctx_data["supported_skills"]),
            resume_artifact=resume_path, cover_letter=ctx_data.get("cover_letter", ""),
            llm=RemoteLLMProvider(client), role=ctx_data.get("role", ""))

        with playwright_session(headless=HEADLESS) as page:   # isolated context per task (§35)
            runner.run_task(task, page, ctx, submit=submit)

        client.post(f"/worker/tasks/{task.id}/complete", json={
            "worker_id": WORKER_ID, "status": task.status.value,
            "questions": [q.model_dump() for q in task.questions],
            "logs": [e.model_dump() for e in task.logs],
            "current_page": task.current_page, "error_code": task.error_code,
            "error_message": task.error_message,
            "confirmation_reference": task.confirmation_reference,
            "started_at": task.started_at, "submitted_at": task.submitted_at,
            "finished_at": task.finished_at,
        }).raise_for_status()
        print(f"[worker] task {task.id} -> {task.status.value}", flush=True)
    except httpx.HTTPStatusError as e:
        if e.response.status_code == 409:
            # The API already moved this task on without us — almost always its own stale-
            # claim recovery deciding we'd gone quiet (a slow/cold-starting API can delay our
            # heartbeats past its timeout even though the run itself is still fine) and
            # requeuing or flagging the task itself. That is NOT our crash to report: posting
            # /fail would just 409 again (the task isn't CLAIMED anymore either) and would
            # overwrite whatever outcome the API already recorded with a misleading one.
            print(f"[worker] task {task.id}: API already resolved this claim (409) — "
                  "leaving its recovered status as-is", flush=True)
        else:
            _report_crash(client, task, e)
    except Exception as e:  # noqa: BLE001 — report and move on; the API decides recovery (§18)
        _report_crash(client, task, e)
    finally:
        hb_stop.set()
        hb_thread.join(timeout=2)
        if resume_path and os.path.exists(resume_path):
            os.remove(resume_path)             # never leave résumé PDFs on the Mac (§8)


# ----------------------------------------------------------------- main loop #
def run() -> int:
    if not API_BASE or not TOKEN:
        print("[worker] API_BASE_URL and WORKER_AUTH_TOKEN are required", file=sys.stderr)
        return 2
    signal.signal(signal.SIGINT, _handle_stop)
    signal.signal(signal.SIGTERM, _handle_stop)

    headers = {"Authorization": f"Bearer {TOKEN}"}
    print(f"[worker] {WORKER_ID} -> {API_BASE} (poll {POLL_SECONDS}s)", flush=True)
    idle_wait = POLL_SECONDS
    with httpx.Client(base_url=API_BASE, headers=headers, timeout=60.0) as client:
        while not _stop:
            try:
                client.post("/worker/heartbeat",
                            json={"worker_id": WORKER_ID, "status": "idle"})
                r = client.post("/worker/tasks/claim", json={"worker_id": WORKER_ID})
                if r.status_code == 200:
                    _process(client, r.json())
                    idle_wait = POLL_SECONDS       # reset backoff after doing work (§16)
                    continue
                if r.status_code not in (204,):
                    print(f"[worker] claim {r.status_code}: {r.text[:200]}", flush=True)
            except httpx.HTTPError as e:
                print(f"[worker] api unreachable: {e}", flush=True)
            # No task (or a transient error): back off, capped, so we don't hammer the API.
            time.sleep(idle_wait)
            idle_wait = min(idle_wait * 2, IDLE_MAX_SECONDS)
    print("[worker] stopped", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
